### ISSUE TITLE
How to add google auth login?

### ISSUE THREAD

**Issue by andresionek91** [villasv/turbine#118]
I tried some changes to the .yml file, but now I'm getting connection refused. I think that I didn't do it right.

1 - added some variables:
```
  GoogleClientId:
    Description: The Google Client Id for Authentication.
    Type: String
  GoogleClientSecret:
    Description: The Google Client Secret for Authentication.
    Type: String
  DomainAuth:
    Description: The domain address that will be allowed to log in with Google Authentication
    Type: String
    Default: example.com
```

2 - Added google auth to installation:
```
install:
              command: |
                PYCURL_SSL_LIBRARY=openssl pip3 install \
                  --no-cache-dir --compile --ignore-installed \
                  pycurl
                SLUGIFY_USES_TEXT_UNIDECODE=yes pip3 install \
                  apache-airflow[celery,postgres,s3,all_dbs,crypto,\
                  google_auth,hdfs,hive,jdbc,kubernetes,ldap,password,\
                  rabbitmq,postgres,s3,ssh]==1.10.2 \
                  celery[sqs] \
                  billiard==3.5.0.4 \
                  tenacity==4.12.0 \
                  asn1crypto==0.24.0 \
                  boto3==1.9.128 \
                  botocore==1.12.128 \
                  pytest==4.4.0 \
                  requests==2.21.0 \
                  watchtower==0.5.5 \
                  pandas==0.24.2 \
                  numpy==1.16.1 \
                  scipy==1.2.1 \
                  sklearn==0.20.3 \
                  dask[complete]==1.1.5
```
3 - Added env vars to airflow:
```
            /etc/sysconfig/airflow:
              content: !Sub
                - |
                  AWS_DEFAULT_REGION=${AWS::Region}
                  AIRFLOW_HOME=/airflow
                  AIRFLOW__CORE__EXECUTOR=CeleryExecutor
                  AIRFLOW__CORE__LOAD_EXAMPLES=${LoadExampleDags}
                  TURBINE__CORE__LOAD_DEFAULTS=${LoadDefaultConns}
                  AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://${DbMasterUsername}:${DbMasterPassword}@${rds}/airflow
                  AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://${LogsBucket}
                  AIRFLOW__CORE__REMOTE_LOGGING=True
                  AIRFLOW__WEBSERVER__BASE_URL=http://INJECTHOST:${WebserverPort}
                  AIRFLOW__WEBSERVER__WEB_SERVER_PORT=${WebserverPort}
                  AIRFLOW__CELERY__BROKER_URL=sqs://
                  AIRFLOW__CELERY__DEFAULT_QUEUE=${queue}
                  AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://${DbMasterUsername}:${DbMasterPassword}@${rds}/airflow
                  AIRFLOW__CELERY__WORKER_CONCURRENCY=${WorkerConcurrency}
                  AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__REGION=${AWS::Region}
                  AIRFLOW__WEBSERVER_AUTHENTICATE=False
                  AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.google_auth
                  AIRFLOW__GOOGLE__CLIENT_ID=${GoogleClientId}
                  AIRFLOW__GOOGLE__CLIENT_SECRET=${GoogleClientSecret}
                  AIRFLOW__GOOGLE__OAUTH_CALLBACK_ROUTE=/oauth2callback
                  AIRFLOW__GOOGLE__DOMAIN=${DomainAuth}
```
Can you help?
