### ISSUE TITLE
Deployment Not Working As Expected

### ISSUE THREAD

**Issue by micah-williamson** [villasv/turbine#192]
I am trying to follow the deployment exactly as described in the readme. I've copied the example project and makefile and am producing a deployment package with the scripts directory in the root of the archive.

<img width="650" alt="Screen Shot 2020-09-30 at 11 03 41 AM" src="https://user-images.githubusercontent.com/4390732/94710628-a9e85a80-030c-11eb-935e-028271876fd8.png">

The appspec has not changed:

```
version: 0.0
os: linux
files:
  - source: /
    destination: /src
hooks:
  ApplicationStart:
    - location: scripts/cdapp_start.sh
      runas: root
  ApplicationStop:
    - location: scripts/cdapp_stop.sh
      runas: root
```

But when deploying I get an error that the stop script is missing:

<img width="726" alt="Screen Shot 2020-09-30 at 11 05 13 AM" src="https://user-images.githubusercontent.com/4390732/94710797-e1ef9d80-030c-11eb-8fd7-1e79501527a4.png">

> Script does not exist at specified location: /opt/codedeploy-agent/deployment-root/.../deployment-archive/scripts/cdapp_stop.sh

I was expecting it to just work out of the box and haven't dug in much myself. Hoping there is a quick response showing me what I did wrong but I'll update once I figure it out.
